### ISSUE TITLE
```featvis``` function doesn't produce image output

### ISSUE THREAD

**Issue by imzhangjinming** [HRI-EU/GDL4DesignApps#3]
The development team of GDL4DesignApps,

Hello, first of all thanks for your great work on autoencoder software development, I'm trying to use autoencoders in my research work, but I'm a bit confused about the ```featvis``` function.

https://github.com/HRI-EU/GDL4DesignApps/blob/9496f3242af069a98bd36b31c58a58f69415d056/gdl4designapps/designapps.py#L622-L642

In the function doc string, the ```plot``` parameter is used to specify whether to plot and store the visualizations as images, but in the source code, this parameter seems to have never been used.

In the example, the code calling this function also does not give picture output

```
## Visualize the latent features
# In this case, we pre-visualized the features and display here the ones the map the rear of the car shapes.
feat_rear = [0, 8, 9, 10, 11, 12, 14, 15, 22, 53]
print("Selected features")
feat_batch = DesignApps.featvis("pcae_training_config.py", sess, S_in,
                                feat_layer, pcs_initial, flags, 
                                dpout=None, gamma_n=None, GPUid=-1, plot=True)
```

There is no image of feature visualizations displayed in the output window
![image](https://user-images.githubusercontent.com/60952516/221457132-31be62df-cc8b-4293-9118-0630d9984f46.png)

Did I misunderstand the usage of this function or could you please show how to correctly do feature visualization in GDL4DesignApps?

Best regards,
Jinming.

**Comment by thrios** [comment]
Dear @imzhangjinming,
thanks for pointing that out! You are right, the code for plotting the shapes is missing.
I'll correct that and upload the updated scripts.
Best
Thiago

**Comment by thrios** [comment]
Dear @imzhangjinming ,

I updated the feature visualization function and added the lines for [plotting and saving the images after computing the shape features](https://github.com/HRI-EU/GDL4DesignApps/blob/0629ff29d153592c3af54aa9e038615a6073c7a0/gdl4designapps/designapps.py#L719).

Let me know how it goes!

Best
Thiago

**Comment by imzhangjinming** [comment]
Dear @thrios ,

Cool! It works. Thank you for the updation!

Now I'll close this issue.

Best
Jinming
